environment:
  matrix:
    - nodejs_version: '14'
    - nodejs_version: '16'
    - nodejs_version: '18'

install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  - ps: Install-Product node $env:nodejs_version
  - npm i npminstall@5 && node_modules\.bin\npminstall

test_script:
  - node --version
  - npm --version
  - npm run test

build: off
services:
  - redis-server
